name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        
      - name: SAST (Static Application Security Testing) with CodeQL
        uses: github/codeql-action/analyze@v2
      #
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t shippusi/pygoat:latest .

      - name: Push Docker Image
        run: docker push shippusi/pygoat:latest
        
      - name: Container Image Scanning with Trivy
        run: |
          # Install Trivy
          wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.tar.gz
          tar zxvf trivy_0.19.2_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/trivy
      
          # Docker login
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
          # Scan Docker image
          trivy shippusi/pygoat:latest
